learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name= 'basic_app'

urlpatterns=[

    path('register/',views.register,name='register'),
    path('user_login',views.user_login,name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('logout',views.user_logout,name='logout'),
    path('special',views.special,name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
# Create your views here.
from basic_app.forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

@login_required
def user_logout(request):
    logout(request)
    # return HttpResponseRedirect(reverse('index'))
    return index(request)

@login_required
def special(request):
    return HttpResponse('You are logged in ')

def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered=False

    if request.method=='POST':
        user_form=UserForm(request.POST)
        profile_form=UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{
                                'registered':registered,
                                'user_form':user_form,
                                'profile_form':profile_form,
    })


def user_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                # return HttpResponseRedirect(reverse('index'))
                return index(request)
            else:
                return HttpResponse('Account not active')

        else:
            print('Someone try to login and failed')
            print("Username was {} and password {}".format(username,password))
            return HttpResponse('Login failed')
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
  <nav class="navbar navbar-inverse ">
    <div class="container">

      <ul class="nav navbar-nav">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1200px-Bootstrap_logo.svg.png" width="30" height="30" alt="">
        <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

        {% if user.is_authenticated %}
        <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
      <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
      {% endif %}
      </ul>
    </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html'%}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to Django</h1>
<h1>You can register and login with sha256 encryption!</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Username">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Password">
    <input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html'%}
{% load static%}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for Registering</h1>
      {% else %}

    <h1>Register here!</h1>
    <h3>Fill Out the form:</h3>
    <form enctype="multipart/form-data" method="post">
      {{ user_form.as_p }}
      {%csrf_token%}
      {{ profile_form.as_p }}
      <input class=" btn btn-primary" type="submit" name="" value="Register">
    </form>
    {% endif %}
  </div>

{% endblock %}